---
deploy:
  tasks:
    - cd /home/piyush/public_html/repositories/tms

    # Pull latest code from GitHub
    - git pull origin main

    # Fix ownership and permissions after Git pull
    - find /home/piyush/public_html/repositories/tms -type d -exec chmod 755 {} \;
    - find /home/piyush/public_html/repositories/tms -type f -exec chmod 644 {} \;
    - chown -R piyush:piyush /home/piyush/public_html/repositories/tms

    # Optional: Laravel cache clearing if using Laravel
    - if [ -f artisan ]; then php artisan config:clear; fi
    - if [ -f artisan ]; then php artisan cache:clear; fi
    - if [ -f artisan ]; then php artisan route:clear; fi
    - if [ -f artisan ]; then php artisan view:clear; fi

    - echo "Deployment complete, ownership and permissions fixed."
