deploy:
  tasks:
    - export DEPLOY_DIR=/home/piyush/public_html/repositories/tms
    - echo "Pulling latest code from GitHub..."
    - cd $DEPLOY_DIR
    - git reset --hard HEAD
    - git pull origin main
    - echo "Deployment complete!"