---
deploy:
  tasks:
    # Navigate to the repo
    - cd /home/piyush/public_html/repositories/tms

    # Pull latest code from GitHub via SSH (replace remote URL if needed)
    - git pull origin main

    # Finish
    - echo "Deployment complete. Tracked files updated, .env and untracked files are safe."